name = "sub"
main = "src/worker.ts"
compatibility_date = "2023-08-14"

kv_namespaces = [
  { binding = "settings", id = "81a60b6377434ba4bc4a97629fc74405", preview_id = "97b679df57f44ef39334f21ab2f77ef5" }
]
